## 넘파이

In [1]:
import numpy as np

### 1, 2, 3차열 배열 생성 및 차원 확인

In [5]:
arr1 = np.arange(8)
arr2 = arr1.reshape(2,4)
arr3 = arr1.reshape(2,2,2)
print(arr1,arr2,arr3)
print(f'{arr1.ndim}차원, {arr2.ndim}차원, {arr3.ndim}차원')

[0 1 2 3 4 5 6 7] [[0 1 2 3]
 [4 5 6 7]] [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
1차원, 2차원, 3차원


In [7]:
print(arr1.dtype)
a1 = arr1.astype('float64')
a1, a1.dtype

int32


(array([0., 1., 2., 3., 4., 5., 6., 7.]), dtype('float64'))

#### 과제_0913_1  
arange, zeros, ones로 배열을 다양하게 생성하세요.

In [46]:
a1 = np.arange(12)
a2 = a1.reshape(3,4)
a3 = a1.reshape(2,2,3)
print(a1,'\n','\n',a2,'\n','\n',a3)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 
 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
 
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [50]:
z1 = np.zeros((5,5), dtype='int32')
o1 = np.ones((2,3,3))
print(z1,'\n','\n',o1)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] 
 
 [[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [51]:
# a1으로 1,2,3차원 배열을 만드세요.(reshape 사용)
a1 = np.arange(25)

a2 = a1.reshape(5,5)
a3 = a1.reshape(5,5,1)

print(a1,'\n','\n',a2,'\n','\n',a3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24] 
 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 
 
 [[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]
  [13]
  [14]]

 [[15]
  [16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]
  [24]]]


#### 과제_0913_2
a1,a2,a3에서 원하는 원소값들을 다양한 방식으로 인덱싱하여 출력하세요.

In [52]:
ar1d[5:]

array([6, 7, 8, 9])

In [55]:
ar1d[-4:]

array([6, 7, 8, 9])

In [56]:
ar1d[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [58]:
ar1d[:-4]

array([1, 2, 3, 4, 5])

In [12]:
# 불린 인덱싱
ar1d = np.arange(1,10)
ar1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# 불린 인덱싱 : [6,7,8,9] 추출
ar = ar1d[ar1d > 5]
ar

array([6, 7, 8, 9])

In [16]:
# 일반 인덱싱
indexes = np.array([5,6,7,8])
ar2 = ar1d[indexes]
ar2

array([6, 7, 8, 9])

### 정렬

In [17]:
#np.sort()

ar = np.array([3,1,9,5])
s1 = np.sort(ar)
print(s1)
print(ar)

# ndarray.sort() 정렬, 원본 반영
# ar 자체를 sort하니까 s2에 저장값 없음
s2 = ar.sort()
print(s2)
print(ar)

[1 3 5 9]
[3 1 9 5]
None
[1 3 5 9]


In [18]:
# 내림차순
s1[::-1]

array([9, 5, 3, 1])

#### 과제_0913_3 
ar2d를 로우 방향, 컬럼 방향으로 정렬하세요. 

In [63]:
ar2d = np.arange(9).reshape(3,3)
ar2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [64]:
ar2d_axis0 = np.sort(ar2d, axis=0) # 로우
ar2d_axis1 = np.sort(ar2d, axis=1) # 컬럼
print(ar2d_axis0,'\n','\n',ar2d_axis1)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 
 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 과제_0913_4
성적 오름차순으로 이름을 출력하세요. (np.argsort()를 이용)

argsort() -> 정렬 시 원본 행렬의 인덱스 값

In [65]:
name_array = np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array = np.array([78,95,84,98,88])

In [66]:
sort_score = np.argsort(score_array)
print(sort_score)

[0 2 4 1 3]


In [68]:
name_array[sort_score]

array(['John', 'Sarah', 'Samuel', 'Mike', 'Kate'], dtype='<U6')

In [20]:
# 선형대수 연산 - 행렬 내적
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(3,2)
dot_product = np.dot(a,b)
dot_product

array([[ 58,  64],
       [139, 154]])

In [23]:
# 전치 행렬
print(a,'\n')
transpose_mat = np.transpose(a)
transpose_mat

[[1 2 3]
 [4 5 6]] 



array([[1, 4],
       [2, 5],
       [3, 6]])

## 판다스

In [2]:
import pandas as pd
tdf = pd.read_csv('titanic_train.csv')
tdf.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [25]:
tdf.shape

(891, 12)

In [26]:
tdf.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [27]:
tdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [29]:
vcounts = tdf['Pclass'].value_counts()
vcounts

3    491
1    216
2    184
Name: Pclass, dtype: int64

### 데이터 프레임과 리스트, 딕셔너리, ndarray 상호 변환

#### 과제_0913_5 
데이터 프레임과 리스트, 딕셔너리, ndarray 상호 변환 사례를 작성하여 설명하세요.

In [3]:
import numpy as np

col_name1 = ['col1']
list1 = [1,2,3]
array1 = np.array(list1)
print('array1 shape:', array1.shape)
df_list1 = pd.DataFrame(list1, columns=col_name1)
print('1차원 : list -> DataFrame \n', df_list1)
df_array1 = pd.DataFrame(array1, columns=col_name1)
print('1차원 : array -> DataFrame \n', df_array1)

array1 shape: (3,)
1차원 : list -> DataFrame 
    col1
0     1
1     2
2     3
1차원 : array -> DataFrame 
    col1
0     1
1     2
2     3


In [10]:
dfli1 = pd.DataFrame(list1)
dfli1

0
0  1
1  2
2  3

In [12]:
dfar1 = pd.DataFrame(array1)
dfar1

0
0  1
1  2
2  3

In [4]:
col_name2 = ['col1','col2','col3']

list2 = [[1,2,3],
        [11,12,13]]
array2 = np.array(list2)
print('array2 shape:', array2.shape)
df_list2 = pd.DataFrame(list2,columns=col_name2)
print('2차원 : list -> DataFrame \n', df_list2)
df_array2 = pd.DataFrame(array2, columns=col_name2)
print('2차원 : array -> DataFrame \n', df_array2)

array2 shape: (2, 3)
2차원 : list -> DataFrame 
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 : array -> DataFrame 
    col1  col2  col3
0     1     2     3
1    11    12    13


In [13]:
dfli2 = pd.DataFrame(list2)
dfli2

0   1   2
0   1   2   3
1  11  12  13

In [16]:
dict1 = {'col1':[1,11],'col2':[2,22],'col3':[3,33]}
df_dict = pd.DataFrame(dict1)
df_dict

col1  col2  col3
0     1     2     3
1    11    22    33

In [6]:
array3 = df_dict.values
print(type(array3), array3.shape)
array3

<class 'numpy.ndarray'> (2, 3)


array([[ 1,  2,  3],
       [11, 22, 33]], dtype=int64)

In [17]:
list3 = df_dict.values.tolist()
print(type(list3))
list3

<class 'list'>


[[1, 2, 3], [11, 22, 33]]

In [8]:
dict3 = df_dict.to_dict('list')
print(type(dict3))
dict3

<class 'dict'>


{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}

#### 과제_0913_6
tdf를 전처리 및 탐색적 분석(시각화, 통계적 기법)을 통하여 분석용 데이터셋으로 만드세요.

In [ ]:
d

## 사이킷런
### 사이킷런을 이용하여 붓꽃(iris) 데이터 품종 예측하기

In [31]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [34]:
iris = load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [36]:
iris_data = iris.data
iris_label = iris.target
print(iris.feature_names)
print(iris.target_names)
print(iris_data)
print(iris_label)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3

In [38]:
idf = pd.DataFrame(iris_data, columns=iris.feature_names)
idf['label'] = iris.target
idf.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

#### 과제_0913_7
idf에 대해서 학습용, 평가용 데이터 8:2로 나눠 분류 모델링 dt(decision tree) 및 정확도 평가를 수행하세요.

In [41]:
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label,
                                                   test_size=0.2, random_state=11)
dt_clf = DecisionTreeClassifier(random_state=11)
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier(random_state=11)

In [42]:
pred = dt_clf.predict(X_test)

In [43]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,pred))

0.9333333333333333
