## Numpy

In [31]:
import numpy as np   # numpy는 문자 X 숫자만 다룸

In [4]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [5]:
type(a)

numpy.ndarray

In [6]:
max([1, 2, 3, 4])

4

In [8]:
a.shape    # 4 한개만 나오는 것임 1차원

(4,)

In [ ]:
# numpy에서는 데이터 타입이 엄청 많음
# 정수만 들어감, 100이하의 정수만 들어감 등등
# 데이터 방을 효율적으로 관리하기 위해

In [12]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [13]:
a.shape

(2, 2)

In [14]:
a = np.array([[1, 2, 3], [3, 4, 5]])
a

array([[1, 2, 3],
       [3, 4, 5]])

In [16]:
a.shape      # 2차원으룽 

(2, 3)

In [23]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
a                            # 종이가 두장 겹쳐있는것 처럼

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [22]:
a.shape     # 3차원 

(2, 2, 2)

In [24]:
a = np.array([[[1, 2, 3], [3, 4, 5]], [[5, 6, 7], [7, 8, 9]]])
a

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [25]:
a.shape

(2, 2, 3)

In [28]:
# ( 2, 2, 3 )   ( 2장 있음, 2 X 3 짜리)  ( z , y , x )

In [30]:
np.arange(10)   # output이 array로 나옴

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
# 아하 reshape 사용하면 한줄짜리를 두줄로 바꿀 수 있음

In [33]:
np.arange(12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
np.arange(12).reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [35]:
np.arange(24).reshape(2, 3, 4)  # 3행 4열 짜리가 2장!!  2x3x4=24

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [36]:
np.arange(24).reshape(4, 3, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [37]:
np.arange(36).reshape(3, 4, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [38]:
a = np.array([1, 2, 3, 4])      # element-wise (원소 끼리끼리 연산)
b = np.array([5, 6, 7, 8])      # row-wise (행 끼리끼리)
a + b                           # column-wise (칼럼 끼리끼리)

array([ 6,  8, 10, 12])

In [39]:
a - b

array([-4, -4, -4, -4])

In [43]:
a * b   # 우와 얘는 연산 다해줌 리스트는 더하기만 되는데!!

array([ 5, 12, 21, 32])

In [46]:
c = np.array([10])
c

array([10])

In [48]:
a + c      # 다 더했어 여러개에 다 더함!

array([11, 12, 13, 14])

In [52]:
li = [1, 2, 3, 4, 5]
list(map(lambda x : x*2, li))

[2, 4, 6, 8, 10]

In [53]:
def twice(x):
    return 2*x
list(map(twice, li))

[2, 4, 6, 8, 10]

In [54]:
[1, 2, 3, 4, 5] *2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [55]:
ar = np.array([1, 2, 3, 4, 5])
ar

array([1, 2, 3, 4, 5])

In [56]:
ar * 2

array([ 2,  4,  6,  8, 10])

In [57]:
ar+1

array([2, 3, 4, 5, 6])

In [58]:
a = np.arange(1, 5).reshape(2, 2)
b = np.arange(5, 9).reshape(2, 2)

In [61]:
a

array([[1, 2],
       [3, 4]])

In [62]:
b

array([[5, 6],
       [7, 8]])

In [63]:
a * b

array([[ 5, 12],
       [21, 32]])

In [66]:
a @ b       # 행렬의 곱셈
a.dot(b)
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [ ]:
# inner product(안쪽의 곱셈, 내적) 실수  /  outer product (외적 곱셈) 벡터

In [ ]:
(1, 2) (3,
        4)

In [71]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [76]:
np.eye(4, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [73]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [77]:
a

array([[1, 2],
       [3, 4]])

In [79]:
a.T       # 1, 3, 2, 4로 바뀜 

array([[1, 3],
       [2, 4]])

In [80]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])

In [81]:
a > b

array([False, False,  True,  True])

In [84]:
a > 2         # 참거짓으로 나옴!

array([False, False,  True,  True])

In [86]:
a[a > 2]   # 참만 나오는거

array([3, 4])

np.sort() /  객체.sort() 다른것임 !!

In [88]:
a = np.array([3, 4, 2, 1, 6, 5])
a

array([3, 4, 2, 1, 6, 5])

In [89]:
np.sort(a)

array([1, 2, 3, 4, 5, 6])

In [91]:
a         # 안바뀌어있음 np.sort()

array([3, 4, 2, 1, 6, 5])

In [92]:
a.sort()

In [93]:
a        # 바뀜!! a.sort

array([1, 2, 3, 4, 5, 6])

In [95]:
a[::-1]     # 거꾸로

array([6, 5, 4, 3, 2, 1])

In [101]:
a = np.array([[2, 1, 6], [0, 7, 4], [5, 13, 2]])
a

array([[ 2,  1,  6],
       [ 0,  7,  4],
       [ 5, 13,  2]])

In [103]:
np.sort(a, axis = 0)

array([[ 0,  1,  2],
       [ 2,  7,  4],
       [ 5, 13,  6]])

In [104]:
np.sort(a, axis = 1)

array([[ 1,  2,  6],
       [ 0,  4,  7],
       [ 2,  5, 13]])

In [ ]:
# indexing 인덱싱 파이썬이랑 똑가틈

In [105]:
a

array([[ 2,  1,  6],
       [ 0,  7,  4],
       [ 5, 13,  2]])

In [107]:
a[1, 2] = 14
a

array([[ 2,  1,  6],
       [ 0,  7, 14],
       [ 5, 13,  2]])

In [ ]:
(1 1
 1 1)

In [108]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [113]:
np.ones((2, 2)) * 7

array([[7., 7.],
       [7., 7.]])

In [114]:
np.full((2, 2), 7)

array([[7, 7],
       [7, 7]])

In [115]:
a[1,]

array([ 0,  7, 14])

In [116]:
a[,1]

SyntaxError: invalid syntax (3819423678.py, line 1)

In [117]:
a[:,1]

array([ 1,  7, 13])

In [ ]:
- slicing

In [119]:
# :: < 한칸 건너뛰는거

In [120]:
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [121]:
a[-2:]

array([3, 4])

In [123]:
a[-2:] = [13, 14]
a

array([ 0,  1,  2, 13, 14])

In [124]:
a[-2:] = 11
a

array([ 0,  1,  2, 11, 11])

In [131]:
a = np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [132]:
a[-1:]

array([[20, 21, 22, 23, 24]])

In [151]:
a[:,1]

array([ 1,  6, 11, 16, 21])

In [154]:
a[4, :]

array([20, 21, 22, 23, 24])

In [155]:
a[ :, 1: :2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [156]:
a[1::2, 0:3:2]

array([[ 5,  7],
       [15, 17]])

In [157]:
a = [0, 10, 20, 30, 40, 50, 60, 70]
a[5]

50

In [160]:
a[4:6]

[40, 50]

In [166]:
a = np.array([0, 10, 20, 30, 40, 50, 60, 70])
mask = np.array([0, 1, 1, 0, 0, 1, 0, 0], bool)
mask

array([False,  True,  True, False, False,  True, False, False])

In [167]:
a[mask]

array([10, 20, 50])

In [169]:
a[a > 40]

array([50, 60, 70])

In [171]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [172]:
a[[0,1,2,2],[1,2,0,3]]     # [(0,1)(1,2)(2,0)(2,3)] 요로케 찾음  # Fancy 인덱싱

array([ 1,  6,  8, 11])

In [207]:
a = np.arange(0, 25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [175]:
a[[0,1,2,3],[1,2,3,4]]

array([ 1,  7, 13, 19])

In [182]:
a[range(4),range(1, 5)]

array([ 1,  7, 13, 19])

In [185]:
# 브로드캐스팅   알아서 모양을 맞춰서 계산하는 것

In [186]:
max([1, 2, 3])

3

In [187]:
sum([1, 2, 3])

6

In [210]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [191]:
sum(a)

array([5, 7, 9])

In [193]:
np.sum(a)          # 넘파이로 더하기 해줘야 총 더한게 나옴!

21

In [197]:
np.sum(a, axis = 0)  # 행 방향으로

array([5, 7, 9])

In [196]:
np.sum(a, axis = 1)   #열 방향으로

array([ 6, 15])

In [199]:
#argmin()              /  argmax()
# 제일 작은 인덱스 번호  / 제일 큰 인덱스 번호

In [208]:
np.where(a > 7)    # return index

(array([1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4], dtype=int64),
 array([3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4], dtype=int64))

In [209]:
index = np.where(a > 7)
print(index)
a[index]

(array([1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4], dtype=int64), array([3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4], dtype=int64))


array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [211]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.where(a > 4)

(array([1, 1], dtype=int64), array([1, 2], dtype=int64))

In [213]:
a[np.where(a > 4)]   # 인덱스 괄호에 넣으니까 인덱스넘버 말고 값이 나옴

array([5, 6])

In [220]:
a = np.arange(0, 25).reshape(5, 5)
a[1:3 , : :3]

array([[ 5,  8],
       [10, 13]])

In [221]:
np.sum(a[1:3 , : :3])

36

In [227]:
np.arange(36).reshape(3,4,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [228]:
from datetime import datetime, date, time

In [232]:
dt = datetime.now()
dt

datetime.datetime(2022, 6, 24, 16, 26, 41, 176415)

In [233]:
dt.year

2022

In [235]:
dt.month

6

In [236]:
dt.day

24

In [234]:
dt.hour

16

In [237]:
dt.minute

26

In [238]:
dt.date()

datetime.date(2022, 6, 24)

In [239]:
dt

datetime.datetime(2022, 6, 24, 16, 26, 41, 176415)

In [240]:
dt.strftime("%m/%d/%Y %H:%M")

'06/24/2022 16:26'

In [241]:
datetime.strptime('20091031', '%Y%m%d')

datetime.datetime(2009, 10, 31, 0, 0)

In [243]:
dt2 = datetime.strptime('20091031', '%Y%m%d')
dt2

datetime.datetime(2009, 10, 31, 0, 0)

In [244]:
dt = datetime.now()
dt

datetime.datetime(2022, 6, 24, 16, 34, 50, 868284)

In [247]:
td = dt-dt2   # 타임 델타가 나옴 timedelta 시간 차이
td

datetime.timedelta(days=4619, seconds=59690, microseconds=868284)

In [248]:
dt2 + td

datetime.datetime(2022, 6, 24, 16, 34, 50, 868284)

In [ ]:
# 올해 크리스마스까지 남은 날짜는?

In [256]:
dt = datetime.now()
dt2 = datetime.strptime('20221225', '%Y%m%d')
td = dt2-dt
td

datetime.timedelta(days=183, seconds=26277, microseconds=598803)

In [257]:
td.days

183

In [259]:
print(f"{td.days}일 남았습니다")

183일 남았습니다


## Series

1차원 자료를 Series 라고 한다.

In [1]:
import pandas as pd

In [2]:
pd.Series(["a", "b", "c"])

0    a
1    b
2    c
dtype: object

In [3]:
s = pd.Series(["a", "b", "c"])

In [4]:
s

0    a
1    b
2    c
dtype: object

In [ ]:
#이 라이브러리(Pandas)에서는 object를 글자라고 표현함. string..

In [5]:
s.index

RangeIndex(start=0, stop=3, step=1)

In [6]:
s.values

array(['a', 'b', 'c'], dtype=object)

In [7]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
pd.Series(sdata)

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [ ]:
# Pandas에서는 인덱스가 숫자가 아닌 문자형으로도 출력 됨

In [8]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
s1 = pd.Series(sdata)

In [9]:
type(s1)

pandas.core.series.Series

In [10]:
s1['Ohio']

35000

## DataFrame

표

In [11]:
pd.DataFrame([[1, 2], [3, 4]])        # 리스트 안에 리스트 (중첩 리스트)

0  1
0  1  2
1  3  4

In [12]:
pd.DataFrame([[1, 2], [3, 4]], index = ['a', 'b'])

0  1
a  1  2
b  3  4

In [16]:
# 리스트에서 만들기
pd.DataFrame([[1, 2], [3, 4]], index = ['a', 'b'], columns = ['A', 'B'])

A  B
a  1  2
b  3  4

In [21]:
# 딕셔너리에서 만들기 (columns의 이름이 잡혀있움)(딕셔너리로 하는게 더 많이 쓰임)
pd.DataFrame({'key1': [1, 3], 'key2': [2, 4]})

key1  key2
0     1     2
1     3     4

In [19]:
pd.DataFrame({'key1': [1, 3], 'key2': [2, 4]}, index = ['a','b'])

key1  key2
a     1     2
b     3     4

In [20]:
pd.DataFrame({'A': [1, 3], 'B': [2, 4]}, index = ['a','b'])

A  B
a  1  2
b  3  4