## 빅데이터 기반 AI 응용 솔루션 개발자 전문과정

#### 교과목명 : 분석라이브러리 활용

- 평가일 : 22.7.8
- 성명 : 박혜린
- 점수 :

### Q1. 표준정규분포 기반의 2행 3열 배열을 랜덤하게 생성하여 크기, 자료형, 차원을 출력하세요.

In [2]:
import pandas as pd
import numpy as np

a = np.random.rand(2,3)

print(a)
print(a.shape)
print(a.dtype)
print(a.ndim)

[[0.23935849 0.17092621 0.92116245]
 [0.70529209 0.03135867 0.22654644]]
(2, 3)
float64
2


### Q2. arange(), reshape() 이용 1차원 2차원 3차원 배열을 아래와 같이 생성하세요.
[0 1 2 3 4 5 6 7 8 9]  

[[0 1 2 3 4]  
 [5 6 7 8 9]]  
 
[[[0 1 2 3 4]  
  [5 6 7 8 9]]]

In [6]:
b = np.arange(10)

print(b)
print(b.reshape(2,5))
print(b.reshape(1,2,5))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[[0 1 2 3 4]
  [5 6 7 8 9]]]


### Q3. 1 ~ 100 까지 배열에서 3과 7의 공배수인 것만을 출력하세요.

In [10]:
c = np.arange(1, 101)

c2 = c[(c%3==0) & (c%7==0)]
c2

array([21, 42, 63, 84])

### Q4. 아래 3차원 배열을 생성하여 출력한 후 1차원으로 변환하여 출력하세요.(reshape() 사용)

[[[ 0  1  2  3  4]  
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]  
   [15 16 17 18 19]]

 [[20 21 22 23 24]  
   [25 26 27 28 29]]]

In [31]:
d = np.arange(30).reshape(3,2,5)

print(d)
print(d.reshape(-1))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


### Q5. array2d에서 인덱스를 이용해서 값을 선택하고 리스트로 아래와 같이 출력하세요.
arr2d = np.arange(1,10).reshape(3,3)

[3, 6]  

[[1, 2],  
[4, 5]]

[[1, 2, 3]  
[4, 5, 6]]

In [52]:
arr2d = np.arange(1,10).reshape(3,3)
print(arr2d)


ar1 = arr2d[:2,2]
ar2 = arr2d[:2,:2]
ar3 = arr2d[:2,:3]

print(ar1)
print(ar2)
print(ar3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6]
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]


### Q6. zeros_like, ones_like, full_like 함수 사용 예를 작성하세요.

In [59]:
e = np.arange(10).reshape(2,5)
print(e)

e1 = np.zeros_like(e)
e2 = np.ones_like(e)
e3 = np.full_like(e,5)

print(e1)
print(e2)
print(e3)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[5 5 5 5 5]
 [5 5 5 5 5]]


### Q7. 10 ~ 20 사이의 정수 난수로 10행 5열 2차원 배열을 생성하고 저장한 후 다시 불러내서 출력하세요.

In [76]:
f = np.random.randint(10,21,(2,10,5))
print(f)

np.save('file.npy',f)
np.load('file.npy')

[[[20 18 11 13 16]
  [17 16 18 13 15]
  [13 18 11 16 14]
  [14 17 20 19 12]
  [12 12 13 20 20]
  [17 17 13 18 15]
  [13 13 11 16 14]
  [14 18 12 13 16]
  [19 13 18 15 18]
  [20 17 20 17 19]]

 [[15 17 18 15 18]
  [19 13 13 14 15]
  [18 17 11 12 11]
  [11 16 18 18 20]
  [15 15 15 17 18]
  [18 15 18 17 20]
  [10 12 15 12 10]
  [11 14 10 18 12]
  [14 13 16 19 10]
  [10 10 14 15 11]]]


array([[[20, 18, 11, 13, 16],
        [17, 16, 18, 13, 15],
        [13, 18, 11, 16, 14],
        [14, 17, 20, 19, 12],
        [12, 12, 13, 20, 20],
        [17, 17, 13, 18, 15],
        [13, 13, 11, 16, 14],
        [14, 18, 12, 13, 16],
        [19, 13, 18, 15, 18],
        [20, 17, 20, 17, 19]],

       [[15, 17, 18, 15, 18],
        [19, 13, 13, 14, 15],
        [18, 17, 11, 12, 11],
        [11, 16, 18, 18, 20],
        [15, 15, 15, 17, 18],
        [18, 15, 18, 17, 20],
        [10, 12, 15, 12, 10],
        [11, 14, 10, 18, 12],
        [14, 13, 16, 19, 10],
        [10, 10, 14, 15, 11]]])

### Q8. df = sns.load_dataset('titanic')로 불러와서 다음 작업을 수행한 후 출력하세요.
- 전체 칼럼중 'survived'외에 모든 칼럼을 포함한 df_x를 산출한 후 dataset/df_x.pkl로 저장한다.
- df_x.pkl을 데이터프레임 df_x 이름으로 불러온 후 앞 5개 행을 출력한다. 

In [170]:
import seaborn as sns
df = sns.load_dataset('titanic')

df_x = df.drop('survived', axis=1)

df_x.to_pickle('df_x.pkl')
df_x = pd.read_pickle('df_x.pkl')
df_x

pclass     sex   age  sibsp  parch     fare embarked   class    who  \
0         3    male  22.0      1      0   7.2500        S   Third    man   
1         1  female  38.0      1      0  71.2833        C   First  woman   
2         3  female  26.0      0      0   7.9250        S   Third  woman   
3         1  female  35.0      1      0  53.1000        S   First  woman   
4         3    male  35.0      0      0   8.0500        S   Third    man   
..      ...     ...   ...    ...    ...      ...      ...     ...    ...   
886       2    male  27.0      0      0  13.0000        S  Second    man   
887       1  female  19.0      0      0  30.0000        S   First  woman   
888       3  female   NaN      1      2  23.4500        S   Third  woman   
889       1    male  26.0      0      0  30.0000        C   First    man   
890       3    male  32.0      0      0   7.7500        Q   Third    man   

     adult_male deck  embark_town alive  alone  
0          True  NaN  Southampton    no  False  
1         False    C    Cherbourg   yes  False  
2         False  NaN  Southampton   yes   True  
3         False    C  Southampton   yes  False  
4          True  NaN  Southampton    no   True  
..          ...  ...          ...   ...    ...  
886        True  NaN  Southampton    no   True  
887       False    B  Southampton   yes   True  
888       False  NaN  Southampton    no  False  
889        True    C    Cherbourg   yes   True  
890        True  NaN   Queenstown    no   True  

[891 rows x 14 columns]

### Q9. df = sns.load_dataset('titanic')로 불러와서 deck 열에서 NaN 갯수를 계산하세요.

In [78]:
df = sns.load_dataset('titanic')
df.deck.isnull().sum()

688

### Q10. Q9의 df에서 각 칼럼별 null 개수와 df 전체의 null 개수를 구하세요.

In [81]:
print(df.isnull().sum())
print(df.isnull().sum().sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64
869


### 아래 tdf 데이터프레임에서 Q11 ~ Q12 작업을 수행하세요.

In [87]:
import seaborn as sns
df = sns.load_dataset('titanic')
tdf = df[['survived','sex','age','class']]
tdf.head()

survived     sex   age  class
0         0    male  22.0  Third
1         1  female  38.0  First
2         1  female  26.0  Third
3         1  female  35.0  First
4         0    male  35.0  Third

### Q11. age를 7개 카테고리로 구분하는 새로운 칼럼 'cat_age'를 생성하여 출력하세요. 단, 카테고리 구분을 수행하는 사용자 함수를 만들고 그 함수를 age 칼럼에 매핑하여 결과를 tdf1에 저장하고 출력하세요.

[카테고리]  
age <= 5: cat = 'Baby'  
age <= 12: cat = 'Child'  
age <= 18: cat = 'Teenager'  
age <= 25: cat = 'Student'  
age <= 60: cat = 'Adult'  
age > 60 : cat = 'Elderly'

In [173]:
def catage(age):
    cat = ''
    if age <= 5: cat = 'Baby'
    elif age <= 12: cat = 'Child'
    elif age <= 18: cat = 'Teenager'
    elif age <= 25: cat = 'Student'
    elif age <= 60: cat = 'Adult'
    else: cat = 'Elderly'
    
    return cat

tdf1 = tdf.copy()
tdf1['cat_age'] = tdf.age.apply(catage)
tdf1.head()

survived     sex   age  class  cat_age
0         0    male  22.0  Third  Student
1         1  female  38.0  First    Adult
2         1  female  26.0  Third    Adult
3         1  female  35.0  First    Adult
4         0    male  35.0  Third    Adult

### Q12.  tdf1의 sex, class 칼럼을 '_'으로 연결한 'sc'칼럼을 추가한 후 아래와 같이 출력하세요.



In [175]:
tdf1['sc'] = tdf1[['sex','class']].agg('_'.join, axis=1)
tdf1

survived     sex   age   class  cat_age            sc
0           0    male  22.0   Third  Student    male_Third
1           1  female  38.0   First    Adult  female_First
2           1  female  26.0   Third    Adult  female_Third
3           1  female  35.0   First    Adult  female_First
4           0    male  35.0   Third    Adult    male_Third
..        ...     ...   ...     ...      ...           ...
886         0    male  27.0  Second    Adult   male_Second
887         1  female  19.0   First  Student  female_First
888         0  female   NaN   Third  Elderly  female_Third
889         1    male  26.0   First    Adult    male_First
890         0    male  32.0   Third    Adult    male_Third

[891 rows x 6 columns]

### Q13. join() 메소드는 두 데이터프레임의 행 인덱스를 기준으로 결합한다. 2개의 주식데이터를 가져와서 join() 메소드로 아래와 같이 결합한 후 다음 사항을 수행하세요.
- df1과 df2의 교집합만 출력되도록 결합하여 df3에 저장하고 출력
- df3에서 중복된 칼럼을 삭제한 후 블린 인덱싱을 이용하여 eps가 3000 보다 적거나 stock_name이 이마트인 데이터를 선택하여 데이터프레임을 생성하고 df4 이름으로 저장 및 출력하세요.(단, '<' 와 '==' 를 반드시 사용해야 함)

In [186]:
df1 = pd.read_excel('stock price.xlsx', index_col='id')
df2 = pd.read_excel('stock valuation.xlsx', index_col='id')

In [142]:
df3 = df1.join(df2, how='inner')
df3

stock_name          value   price    name           eps     bps  \
id                                                                       
130960     CJ E&M   58540.666667   98900  CJ E&M   6301.333333   54068   
139480        이마트  239230.833333  254500     이마트  18268.166667  295780   
145990        삼양사   82750.000000   82000     삼양사   5741.000000  108090   
185750        종근당   40293.666667  100500     종근당   3990.333333   40684   
204210     모두투어리츠    3093.333333    3475  모두투어리츠     85.166667    5335   

              per       pbr  
id                           
130960  15.695091  1.829178  
139480  13.931338  0.860437  
145990  14.283226  0.758627  
185750  25.185866  2.470259  
204210  40.802348  0.651359

In [187]:
df3.drop('name', axis=1)

stock_name          value   price           eps     bps        per  \
id                                                                          
130960     CJ E&M   58540.666667   98900   6301.333333   54068  15.695091   
139480        이마트  239230.833333  254500  18268.166667  295780  13.931338   
145990        삼양사   82750.000000   82000   5741.000000  108090  14.283226   
185750        종근당   40293.666667  100500   3990.333333   40684  25.185866   
204210     모두투어리츠    3093.333333    3475     85.166667    5335  40.802348   

             pbr  
id                
130960  1.829178  
139480  0.860437  
145990  0.758627  
185750  2.470259  
204210  0.651359

In [203]:
df4 = df3.copy()
df4 = df4[('eps' < 3000) | ('stock_name'=='이마트')]

TypeError: '<' not supported between instances of 'str' and 'int'

### Q14. 배열 a에 대하여 3차원 자리에 2차원을 2차원 자리에 1차원을 1차원 자리에 3차원을 넣어서 변환하여 출력하세요

In [132]:
a = np.arange(6).reshape(1,2,3)
print(a,a.shape,'\n')

b = np.transpose(a,(1,2,0))
print(b,b.shape)

[[[0 1 2]
  [3 4 5]]] (1, 2, 3) 

[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]] (2, 3, 1)


### Q15. 'mpg'를 'kpl' 로 환산하여 새로운 열을 생성하고 반올림하여 소수점 아래 둘째 자리까지 처음 5개행을 출력하세요.

In [196]:
# read_csv() 함수로 df 생성
import pandas as pd
auto_df = pd.read_csv('./dataset/auto-mpg.csv')
# 열 이름을 지정
auto_df.columns = ['mpg','cylinders','displacement','horsepower','weight',
              'acceleration','model year','origin','name'] 
print(auto_df.head(3)) 


    mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  


In [199]:
auto_df['kpl'] = auto_df['mpg'] / 2.352
auto_df.kpl = auto_df.kpl.round(2)
auto_df.head()

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   

   origin                       name   kpl  
0       1  chevrolet chevelle malibu  7.65  
1       1          buick skylark 320  6.38  
2       1         plymouth satellite  7.65  
3       1              amc rebel sst  6.80  
4       1                ford torino  7.23

### Q16. './dataset/stock-data.csv'를 데이터프레임으로 불러와서 datetime64 자료형으로 변환한 후에 년, 월, 일로 분리하고 year를 인덱스로 셋팅하여 출력하세요.

### Q17. titanic 데이터셋(titanic = sns.load_dataset('titanic'))에서 5개 열을 선택해서 class열을 기준으로 그룹화를 수행한 후 아래와 같이 출력하였다. 다음 사항을 출력하세요.
5개 열 : ['age','sex', 'class', 'fare', 'survived']  
- 그룹별 평균 출력
- 그룹별 최대값 출력

### Q18. titanic 데이터셋에서 'Third'그룹만을 선택해서 group3 이름으로 저장하고 통계요약표를 출력하세요.

In [ ]:
import seaborn as sns
df = sns.load_dataset('titanic')
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

### Q19.  titanic 데이터셋에서 다음 전처리를 수행하세요.
1. df에서 중복 칼럼으로 고려할 수 있는 컬럼들(6개 내외)을 삭제한 후 나머지 컬럼들로 구성되는 데이터프레임을 df1 이름으로 저장 후 출력하세요. 
2. df1에서 null값이 50% 이상인 칼럼을 삭제 후 df2 이름으로 저장하고 출력하세요.
3. df2에서 결측값이 있는 age 칼럼에 대해서 평균값으로 대체 처리를 수행하세요. 
4. df2에서 결측값이 있는 embarked 칼럼에 대해서 앞행의 값으로 대체 처리를 수행하세요. 
5. df2 문자로 되어있는 칼럼들을 레이블 인코딩 수행하여 숫자로 변환 후 df2.info()를 출력하세요

In [ ]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

### Q20. 보스톤 주택가격 데이터를 탐색한 후 가장 중요한 독립변수 2개를 선정하고 그 이유를 시각화하여 설명하세요.

In [ ]:
from sklearn.datasets import load_boston
# boston 데이타셋 로드
boston = load_boston()

# boston 데이타셋 DataFrame 변환 
bostonDF = pd.DataFrame(boston.data , columns = boston.feature_names)

# boston dataset의 target array는 주택 가격임. 이를 PRICE 컬럼으로 DataFrame에 추가함. 
bostonDF['PRICE'] = boston.target
print('Boston 데이타셋 크기 :',bostonDF.shape)
bostonDF.head()

Boston 데이타셋 크기 : (506, 14)


CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  PRICE  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2